version: "3.5"
services:
  beacon-chain:
    build:
      context: ./beacon-chain
      args:
        BEACON_API_PORT: 3500
        UPSTREAM_VERSION: 24.1.0
    environment:
      BEACON_API_PORT: 3500
      CHECKPOINT_SYNC_URL: ""
      P2P_PORT: 9605
      FEE_RECIPIENT_ADDRESS: ""
      EXTRA_OPTS: ""
      JAVA_OPTS: "-Xmx6g"
    volumes:
      - "teku-holesky-data:/opt/teku/data"
    ports:
      - "9605:9605/tcp"
      - "9605:9605/udp"
    restart: unless-stopped
    security_opt:
      - "seccomp:unconfined"
  validator:
    build:
      context: ./validator
      args:
        UPSTREAM_VERSION: 24.1.0
    environment:
      LOG_TYPE: INFO
      BEACON_NODE_ADDR: "http://beacon-chain.teku-holesky.dappnode:3500"
      GRAFFITI: validating_from_DAppNode
      EXTRA_OPTS: ""
      FEE_RECIPIENT_ADDRESS: ""
      JAVA_OPTS: "-Xmx6g"
    restart: unless-stopped
    security_opt:
      - "seccomp:unconfined"
volumes:
  teku-holesky-data: {}
